/**
 * Public URL of the Simple Form feedback form — used by the early-access
 * dialog on the pricing page and by the PlanLockedFallback component
 * shown to Free users on gated routes.
 *
 * Generated by scripts/create-feedback-form.mts at 2026-05-26T07:51:53.108Z.
 * Re-run that script and the constant below will be overwritten.
 */
export const FEEDBACK_FORM_URL =
  process.env.NEXT_PUBLIC_FEEDBACK_FORM_URL ??
  "https://simple-form.dosomething.qzz.io/u/barun-tiwary-m8ix/help-shape-simple-forms-paid-plans-psqj";
