/**
 * Public URL of the Simple Form feedback form — used by the early-access
 * dialog on the pricing page and by the PlanLockedFallback component
 * shown to Free users on gated routes.
 *
 * Generated by scripts/create-feedback-form.mts at 2026-05-26T10:42:12.518Z.
 * Re-run that script and the constant below will be overwritten.
 */
export const FEEDBACK_FORM_URL =
  process.env.NEXT_PUBLIC_FEEDBACK_FORM_URL ??
  "http://localhost:3000/u/barun-tiwary-kjce/help-shape-simple-forms-paid-plans-kpmz";
